# Generated by Django 5.0 on 2023-12-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0004_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_approved', models.BooleanField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Declined')], default=0)),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserRegistration.destination')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserRegistration.user')),
            ],
        ),
    ]
